---
all:
  children:

    master:
      hosts:
        k8s-master:
          ansible_host: 192.168.64.8
          ansible_user: node_master
          ansible_ssh_private_key_file: ~/.ssh/cle1

    workers:
      hosts:
        k8s-worker1:
          ansible_host: 192.168.64.9
          ansible_user: node_client1
          ansible_ssh_private_key_file: ~/.ssh/cle1

        k8s-worker2:
          ansible_host: 192.168.64.10
          ansible_user: node_client2
          ansible_ssh_private_key_file: ~/.ssh/cle1

    k8s_cluster:
      children:
        master:
        workers:
